config/routes.rb
Tabora::Application.routes.draw do

  resources :acts, only: [:update, :destroy]
  resources :battles, only: [:update, :destroy]
  resources :participations, only: [:create, :destroy]
	resources :sessions, only: [:new, :create]

  resources :users, only: [:show, :new, :edit, :create, :update, :destroy]
  resources :games

  resources :events do
		resources :tournaments, only: [:new, :create]
		resources :operators, only: [:new, :create]
	end

	resources :tournaments, only: [:index, :show, :edit, :update, :destroy]
	resources :operators, only: [:destroy]

	get 'login', to: 'sessions#new'
	delete 'logout', to: 'sessions#destroy'
	get 'signup', to: 'users#new'

	root 'events#home'
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
	belongs_to :event
	belongs_to :game
	has_many :participations, dependent: :destroy
	has_many :participants, through: :participations, source: :user
	has_many :battles, dependent: :destroy

	validates :game, presence: true
	validates :event, presence: true

	# Returns name of tournament. If no name is given returns name of game.
	def name
		super || game.name
	end


	def update(tournament_params)
		if super(tournament_params)
			update_phase(tournament_params[:phase]) unless tournament_params[:phase].nil?
			true
		end
	end


	def update_phase(new_phase)
		case new_phase
			when 'ongoing'
				init_battles
			when 'ended'
				nil
		end
	end


	def init_battles
		battle_count = participants.count - 1
		create_battles battle_count
		set_postbattles battle_count
		create_acts
	end

	def create_battles(battle_count)
		(0..battle_count-1).each do |i|
			self.battles.create name:"Battle \##{i+1}"
		end
	end


	def set_postbattles(battle_count)
		(0..battle_count-2).each do |i|
			postbattle_index = (battle_count + 1) / 2 + i / 2
			self.battles[i].postbattles.push self.battles[postbattle_index]
		end
	end


	def create_acts
		randomized = participants.shuffle

		randomized.each.with_index do |participant, i|
			self.battles[i/2].acts.create user:participant
		end
	end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]
	before_action :ensure_that_operator, except: [:index, :show]

  def index
    @tournaments = Tournament.all
  end


  def show
		if current_user and @tournament.phase == 'enroll'
			if current_user.is_participant_of @tournament
				@participation = Participation.find_by user: current_user, tournament: @tournament
			else
				@participation = Participation.new
				@participation.tournament = @tournament
			end
		end
  end


  def new
    @tournament = Tournament.new
		@event = Event.find(params[:event_id])
		@games = Game.all
  end


  def edit
		@games = Game.all
  end


  def create
		params[:tournament][:event_id] = params[:event_id]
		modify_name
		@tournament = Tournament.new(tournament_params)
		@tournament.phase = 'enroll'

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tournament }
			else
				@event = Event.find(params[:event_id])
				@games = Game.all
        format.html { render action: 'new' }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
		modify_name unless params[:tournament][:name].nil?

    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url }
      format.json { head :no_content }
    end
  end

  private
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end


		def modify_name
			name = params[:tournament][:name].strip
			if name.length == 0
				params[:tournament][:name] = nil
			else
				params[:tournament][:name] = name
			end
		end


    def tournament_params
      params.require(:tournament).permit(:name, :event_id, :game_id, :phase)
		end

		def ensure_that_operator
			raise_forbidden if current_user.nil?
			event_id = params[:event_id] || @tournament.event_id
			event = Event.find(event_id)
			raise_forbidden unless current_user.is_operator_of event
		end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_controls.html.erb
<strong>Operator tools:</strong>

<ul>
	<li><%= link_to 'Edit', edit_tournament_path(tournament) %></li>
</ul>

<% if tournament.phase == 'enroll' %>
	<%= form_for tournament, data: { confirm: 'Launch tournament?' } do |f| %>
		<%= f.hidden_field :phase, value: 'ongoing' %>
		<%= f.submit value: 'Launch tournament' %>
	<% end %>
<% end %>
<% if tournament.phase == 'ongoing' %>
	<%= form_for tournament, data: { confirm: 'End tournament?' } do |f| %>
		<%= f.hidden_field :phase, value: 'ended' %>
		<%= f.submit value: 'End tournament' %>
	<% end %>
<% end %>

app/views/tournaments/_form_insides.html.erb
<% if @tournament.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

		<ul>
			<% @tournament.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<div class="field">
	<%= f.label :name %><br>
	<%= f.text_field :name %>
</div>
<div class="field">
	<%= f.label :game_id %><br>
	<%= f.select :game_id, options_from_collection_for_select(@games, :id, :name, selected: @tournament.game_id) %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

app/views/tournaments/_row.html.erb
<tr class="phase-<%= tournament.phase %>">
	<td><%= link_to tournament.name, tournament %></td>
	<td><%= tournament.participations.count %></td>
</tr>

app/views/tournaments/_row_with_phase.html.erb
<tr class="phase-<%= tournament.phase %>">
	<td><%= link_to tournament.name, tournament %></td>
	<td><%= tournament.phase %></td>
	<td><%= tournament.participations.count %></td>
</tr>

app/views/tournaments/edit.html.erb
<h1>Editing tournament</h1>

<%= form_for(@tournament) do |f| %>
	<%= render 'form_insides', f: f %>
<% end %>

<p><%= link_to 'Destroy tournament', @tournament, method: :delete, data: { confirm: 'Are you sure?' } %></p>

<%= link_to 'Cancel', @tournament %>

app/views/tournaments/index.html.erb
<h1>Listing tournaments</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Event</th>
      <th>Game</th>
    </tr>
  </thead>

  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr>
        <td><%= link_to tournament.name, tournament %></td>
        <td><%= link_to tournament.event.name, tournament.event %></td>
        <td><%= link_to tournament.game.name, tournament.game %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tournaments/new.html.erb
<h1>New tournament for <%= @event.name %></h1>

<%= form_for(@tournament, url: event_tournaments_path) do |f| %>
	<%= render 'form_insides', f: f %>
<% end %>


<%= link_to 'Back', tournaments_path %>

app/views/tournaments/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= @tournament.event.name %></p>
<h1><%= @tournament.name %></h1>

<p>
	<strong>Phase:</strong>
	<%= @tournament.phase %>
</p>

<p>
  <strong>Game:</strong>
  <%= @tournament.game.name %>
</p>

<table class="table table-striped table-condensed">
	<thead>
		<tr>
			<th>Participants</th>
		</tr>
	</thead>
	<tbody>
		<% @tournament.participants.each do |participant| %>
			<tr>
				<td><%= participant.username %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<div>
	<% if current_user and @tournament.phase == 'enroll' %>
		<% if current_user.is_participant_of(@tournament) %>
			<%= form_for(@participation, method: :delete) do %>
				<%= submit_tag 'Leave' %>
			<% end %>
		<% else %>
			<%= form_for(@participation) do |f| %>
				<%= f.hidden_field :tournament_id %>
				<%= f.submit value:'Join' %>
			<% end %>
		<% end %>
	<% end %>
</div>


<%= render 'battles/battle', battles: @tournament.battles %>



<% if current_user %>
	<% if current_user.is_operator_of @tournament.event %>
		<div class="controls" id="operator-tools">
			<%= render 'controls', tournament: @tournament %>
		</div>
	<% end %>
<% end %>