config/routes.rb
Tabora::Application.routes.draw do

  resources :acts, only: [:update, :destroy]
  resources :battles, only: [:update, :destroy]
  resources :participations, only: [:create, :destroy]
	resources :sessions, only: [:new, :create]

  resources :users, only: [:show, :new, :edit, :create, :update, :destroy]
  resources :games

  resources :events do
		resources :tournaments, only: [:new, :create]
		resources :operators, only: [:new, :create]
	end

	resources :tournaments, only: [:index, :show, :edit, :update, :destroy]
	resources :operators, only: [:destroy]

	get 'login', to: 'sessions#new'
	delete 'logout', to: 'sessions#destroy'
	get 'signup', to: 'users#new'

	root 'events#home'
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :operators, dependent: :destroy
	has_many :operating_users, through: :operators, source: :user
	has_many :tournaments, dependent: :destroy

	validates :name,
						presence: true,
						uniqueness: true

	def has_enroll_tournaments?
		Tournament.where(event:self, phase:'enroll').any?
	end

	def has_ongoing_tournaments?
		Tournament.where(event:self, phase:'ongoing').any?
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
	before_action :ensure_that_admin, except: [:home, :index, :show, :edit, :update]
	before_action :ensure_that_operator, only: [:edit, :update]

	def home
		@events = Event.all
	end


  def index
    @events = Event.all
  end


  def show
  end


  def new
    @event = Event.new
  end


  def edit
  end


  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end


    def event_params
      params.require(:event).permit(:name)
		end

		def ensure_that_operator
			raise_forbidden if current_user.nil?
			event = Event.find params[:id]
			raise_forbidden unless current_user.is_operator_of event
		end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_controls.html.erb
<strong>Operator tools:</strong>
<ul>
	<li><%= link_to 'New tournament', new_event_tournament_path(event_id: @event.id) %></li>
	<li><%= link_to 'Add operator', new_event_operator_path(event_id: @event.id) %></li>
	<li><%= link_to 'Edit', edit_event_path(@event) %></li>
</ul>
<p>
	<strong>Operators:</strong>
	<% @event.operating_users.each do |operator| %>
		<%= operator.username %>
	<% end %>
</p>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<% if current_user %>
	<% if current_user.is_admin? %>
		<p><%= link_to 'Destroy event', @event, method: :delete, data: { confirm: 'Are you sure?' } %></p>
	<% end %>
<% end %>

<%= link_to 'Cancel', @event %>

app/views/events/home.html.erb
<h1>Tabora</h1>

<h2>Ongoing tournaments</h2>

<% @events.each do |event| %>
	<% if event.has_ongoing_tournaments? %>
		<table class="table table-hover">
			<thead>
				<tr>
					<th><%= link_to event.name, event %></th>
					<th>Participations</th>
				</tr>
			</thead>

			<tbody>
			<% event.tournaments.each do |tournament| %>
				<% if tournament.phase == 'ongoing' %>
					<%= render 'tournaments/row', tournament:tournament %>
				<% end %>
			<% end %>
			</tbody>
		</table>
	<% end %>
<% end %>


<h2>Enroll tournaments</h2>

<% @events.each do |event| %>
	<% if event.has_enroll_tournaments? %>
		<table class="table table-hover">
			<thead>
			<tr>
				<th><%= link_to event.name, event %></th>
				<th>Participations</th>
			</tr>
			</thead>

			<tbody>
				<% event.tournaments.each do |tournament| %>
					<% if tournament.phase == 'enroll' %>
						<%= render 'tournaments/row', tournament: tournament %>
					<% end %>
				<% end %>
			</tbody>
		</table>
	<% end %>
<% end %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.name, event %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if current_user %>
	<% if current_user.is_admin? %>
		<div class="controls" id="admin-tools">
			<strong>Admin tools:</strong>
			<ul>
				<li><%= link_to 'New Event', new_event_path %></li>
			</ul>
		</div>
	<% end %>
<% end %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @event.name %></h1>


<table class="table table-hover">
	<thead>
	<tr>
		<th>Tournament</th>
		<th>Phase</th>
		<th>Participations</th>
	</tr>
	</thead>
	<tbody>
	<% @event.tournaments.each do |tournament| %>
		<%= render 'tournaments/row_with_phase', tournament:tournament %>
	<% end %>
	</tbody>
</table>




<% if current_user %>
	<% if current_user.is_operator_of @event %>
		<div class="controls" id="operator-tools">
			<%= render 'controls' %>
		</div>
	<% end %>
<% end %>